version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/platform.oracle:circleci
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            apt-get -y install python3-venv
            python3 -m venv venv

            . venv/bin/activate
            pip install wheel
            python setup.py sdist
            python setup.py bdist_wheel

            pip install .
            pip install pylint
            pylint tap_oracle -d missing-docstring,invalid-name,line-too-long,too-many-locals,too-few-public-methods,fixme,stop-iteration-return
  test:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/platform.oracle:circleci
    steps:
      - checkout
      - run: 'echo "Hello World"'
